"""
Type stubs for ANTLR-generated SMT-LIB parser files.

These stubs provide type hints for the ANTLR-generated parser classes
without modifying the generated source files.
"""

from typing import Any, List, Optional, TypeVar

T = TypeVar('T')

class ParserRuleContext:
    """Base class for parser rule contexts."""
    start: Any
    stop: Any
    parent: Optional['ParserRuleContext']

    def getText(self) -> str: ...
    def getInputStream(self) -> Any: ...

class TerminalNode:
    """Terminal node in parse tree."""
    def getText(self) -> str: ...

class ErrorNode(TerminalNode):
    """Error node in parse tree."""
    ...

class InputStream:
    """Character stream from string."""
    def __init__(self, data: str) -> None: ...

class FileStream(InputStream):
    """Character stream from file."""
    def __init__(self, path: str, encoding: str = "utf-8") -> None: ...

class CommonTokenStream:
    """Token stream for parser."""
    def __init__(self, lexer: Any) -> None: ...

class Lexer:
    """Base lexer class."""
    def removeErrorListeners(self) -> None: ...
    def addErrorListener(self, listener: Any) -> None: ...

class Parser:
    """Base parser class."""
    def removeErrorListeners(self) -> None: ...
    def addErrorListener(self, listener: Any) -> None: ...

# SMT-LIB Lexer
class SMTLIBv2Lexer(Lexer):
    """Generated SMT-LIB lexer."""
    ...

# SMT-LIB Parser
class SMTLIBv2Parser(Parser):
    """Generated SMT-LIB parser."""

    class StartContext(ParserRuleContext):
        """Start rule context."""
        def script(self) -> 'SMTLIBv2Parser.ScriptContext': ...

    class ScriptContext(ParserRuleContext):
        """Script rule context."""
        def command(self) -> List['SMTLIBv2Parser.CommandContext']: ...

    class CommandContext(ParserRuleContext):
        """Command rule context."""
        def cmd_assert(self) -> Optional['SMTLIBv2Parser.Cmd_assertContext']: ...
        def cmd_assertSoft(self) -> Optional['SMTLIBv2Parser.Cmd_assertSoftContext']: ...
        def cmd_declareConst(self) -> Optional['SMTLIBv2Parser.Cmd_declareConstContext']: ...
        def cmd_declareFun(self) -> Optional['SMTLIBv2Parser.Cmd_declareFunContext']: ...
        def cmd_define(self) -> Optional['SMTLIBv2Parser.Cmd_defineContext']: ...
        def cmd_defineConst(self) -> Optional['SMTLIBv2Parser.Cmd_defineConstContext']: ...
        def cmd_defineFun(self) -> Optional['SMTLIBv2Parser.Cmd_defineFunContext']: ...
        def cmd_defineFunRec(self) -> Optional['SMTLIBv2Parser.Cmd_defineFunRecContext']: ...
        def cmd_defineFunsRec(self) -> Optional['SMTLIBv2Parser.Cmd_defineFunsRecContext']: ...
        def cmd_checkSat(self) -> Optional['SMTLIBv2Parser.Cmd_checkSatContext']: ...
        def cmd_checkSatAssuming(self) -> Optional['SMTLIBv2Parser.Cmd_checkSatAssumingContext']: ...
        def cmd_getValue(self) -> Optional['SMTLIBv2Parser.Cmd_getValueContext']: ...
        def cmd_push(self) -> Optional['SMTLIBv2Parser.Cmd_pushContext']: ...
        def cmd_pop(self) -> Optional['SMTLIBv2Parser.Cmd_popContext']: ...
        def cmd_simplify(self) -> Optional['SMTLIBv2Parser.Cmd_simplifyContext']: ...
        def cmd_minimize(self) -> Optional['SMTLIBv2Parser.Cmd_minimizeContext']: ...
        def cmd_maximize(self) -> Optional['SMTLIBv2Parser.Cmd_maximizeContext']: ...
        def cmd_display(self) -> Optional['SMTLIBv2Parser.Cmd_displayContext']: ...
        def cmd_eval(self) -> Optional['SMTLIBv2Parser.Cmd_evalContext']: ...
        def term(self) -> Optional['SMTLIBv2Parser.TermContext']: ...
        def attribute(self) -> List['SMTLIBv2Parser.AttributeContext']: ...

    class TermContext(ParserRuleContext):
        """Term rule context."""
        def ParOpen(self) -> List[Any]: ...
        def ParClose(self) -> List[Any]: ...
        def GRW_Exclamation(self) -> Optional[Any]: ...
        def GRW_Let(self) -> Optional[Any]: ...
        def GRW_Forall(self) -> Optional[Any]: ...
        def GRW_Exists(self) -> Optional[Any]: ...
        def GRW_Match(self) -> Optional[Any]: ...
        def GRW_Underscore(self) -> Optional[Any]: ...
        def spec_constant(self) -> Optional['SMTLIBv2Parser.Spec_constantContext']: ...
        def qual_identifier(self) -> Optional['SMTLIBv2Parser.Qual_identifierContext']: ...
        def term(self) -> List['SMTLIBv2Parser.TermContext']: ...
        def sorted_var(self) -> List['SMTLIBv2Parser.Sorted_varContext']: ...
        def var_binding(self) -> List['SMTLIBv2Parser.Var_bindingContext']: ...
        def match_case(self) -> List['SMTLIBv2Parser.Match_caseContext']: ...
        def attribute(self) -> List['SMTLIBv2Parser.AttributeContext']: ...
        def numeral(self) -> List[Any]: ...

    class Spec_constantContext(ParserRuleContext):
        """Spec constant rule context."""
        def numeral(self) -> Optional[Any]: ...
        def decimal(self) -> Optional[Any]: ...
        def hexadecimal(self) -> Optional[Any]: ...
        def binary(self) -> Optional[Any]: ...
        def string(self) -> Optional[Any]: ...
        def b_value(self) -> Optional[Any]: ...
        def reg_const(self) -> Optional[Any]: ...

    class Qual_identifierContext(ParserRuleContext):
        """Qualified identifier context."""
        def identifier(self) -> Optional['SMTLIBv2Parser.IdentifierContext']: ...
        def ParOpen(self) -> Optional[Any]: ...
        def GRW_As(self) -> Optional[Any]: ...
        def sort(self) -> Optional['SMTLIBv2Parser.SortContext']: ...
        def ParClose(self) -> Optional[Any]: ...

    class IdentifierContext(ParserRuleContext):
        """Identifier context."""
        def symbol(self) -> Optional['SMTLIBv2Parser.SymbolContext']: ...
        def ParOpen(self) -> Optional[Any]: ...
        def GRW_Underscore(self) -> Optional[Any]: ...
        def index(self) -> List['SMTLIBv2Parser.IndexContext']: ...
        def ParClose(self) -> Optional[Any]: ...

    class SymbolContext(ParserRuleContext):
        """Symbol context."""
        def simpleSymbol(self) -> Optional['SMTLIBv2Parser.SimpleSymbolContext']: ...
        def quotedSymbol(self) -> Optional['SMTLIBv2Parser.QuotedSymbolContext']: ...

    class SimpleSymbolContext(ParserRuleContext):
        """Simple symbol context."""
        ...

    class QuotedSymbolContext(ParserRuleContext):
        """Quoted symbol context."""
        ...

    class SortContext(ParserRuleContext):
        """Sort context."""
        def identifier(self) -> 'SMTLIBv2Parser.IdentifierContext': ...
        def sort(self) -> List['SMTLIBv2Parser.SortContext']: ...

    class Sorted_varContext(ParserRuleContext):
        """Sorted variable context."""
        def symbol(self) -> 'SMTLIBv2Parser.SymbolContext': ...
        def sort(self) -> 'SMTLIBv2Parser.SortContext': ...

    class Var_bindingContext(ParserRuleContext):
        """Variable binding context."""
        def symbol(self) -> 'SMTLIBv2Parser.SymbolContext': ...
        def term(self) -> 'SMTLIBv2Parser.TermContext': ...

    class AttributeContext(ParserRuleContext):
        """Attribute context."""
        def keyword(self) -> 'SMTLIBv2Parser.KeywordContext': ...
        def attribute_value(self) -> Optional['SMTLIBv2Parser.Attribute_valueContext']: ...

    class KeywordContext(ParserRuleContext):
        """Keyword context."""
        ...

    class Attribute_valueContext(ParserRuleContext):
        """Attribute value context."""
        ...

    class IndexContext(ParserRuleContext):
        """Index context."""
        def numeral(self) -> Optional[Any]: ...
        def symbol(self) -> Optional['SMTLIBv2Parser.SymbolContext']: ...

    class Match_caseContext(ParserRuleContext):
        """Match case context."""
        ...

    class Function_defContext(ParserRuleContext):
        """Function definition context."""
        def symbol(self) -> 'SMTLIBv2Parser.SymbolContext': ...
        def sorted_var(self) -> List['SMTLIBv2Parser.Sorted_varContext']: ...
        def sort(self) -> 'SMTLIBv2Parser.SortContext': ...
        def term(self) -> 'SMTLIBv2Parser.TermContext': ...

    class Function_decContext(ParserRuleContext):
        """Function declaration context."""
        def symbol(self) -> 'SMTLIBv2Parser.SymbolContext': ...
        def sorted_var(self) -> List['SMTLIBv2Parser.Sorted_varContext']: ...
        def sort(self) -> 'SMTLIBv2Parser.SortContext': ...

    # Command-specific contexts
    class Cmd_assertContext(ParserRuleContext): ...
    class Cmd_assertSoftContext(ParserRuleContext): ...
    class Cmd_declareConstContext(ParserRuleContext): ...
    class Cmd_declareFunContext(ParserRuleContext): ...
    class Cmd_defineContext(ParserRuleContext): ...
    class Cmd_defineConstContext(ParserRuleContext): ...
    class Cmd_defineFunContext(ParserRuleContext): ...
    class Cmd_defineFunRecContext(ParserRuleContext): ...
    class Cmd_defineFunsRecContext(ParserRuleContext): ...
    class Cmd_checkSatContext(ParserRuleContext): ...
    class Cmd_checkSatAssumingContext(ParserRuleContext): ...
    class Cmd_getValueContext(ParserRuleContext): ...
    class Cmd_pushContext(ParserRuleContext): ...
    class Cmd_popContext(ParserRuleContext): ...
    class Cmd_simplifyContext(ParserRuleContext): ...
    class Cmd_minimizeContext(ParserRuleContext): ...
    class Cmd_maximizeContext(ParserRuleContext): ...
    class Cmd_displayContext(ParserRuleContext): ...
    class Cmd_evalContext(ParserRuleContext): ...

    def start(self) -> StartContext: ...

# Visitor base class
class SMTLIBv2Visitor:
    """Generated visitor base class."""

    def visitStart(self, ctx: SMTLIBv2Parser.StartContext) -> Any: ...
    def visitScript(self, ctx: SMTLIBv2Parser.ScriptContext) -> Any: ...
    def visitCommand(self, ctx: SMTLIBv2Parser.CommandContext) -> Any: ...
    def visitTerm(self, ctx: SMTLIBv2Parser.TermContext) -> Any: ...
    def visitSpec_constant(self, ctx: SMTLIBv2Parser.Spec_constantContext) -> Any: ...
    def visitQual_identifier(self, ctx: SMTLIBv2Parser.Qual_identifierContext) -> Any: ...
    def visitIdentifier(self, ctx: SMTLIBv2Parser.IdentifierContext) -> Any: ...
    def visitSymbol(self, ctx: SMTLIBv2Parser.SymbolContext) -> Any: ...
    def visitSimpleSymbol(self, ctx: SMTLIBv2Parser.SimpleSymbolContext) -> Any: ...
    def visitQuotedSymbol(self, ctx: SMTLIBv2Parser.QuotedSymbolContext) -> Any: ...
    def visitSort(self, ctx: SMTLIBv2Parser.SortContext) -> Any: ...
    def visitSorted_var(self, ctx: SMTLIBv2Parser.Sorted_varContext) -> Any: ...
    def visitVar_binding(self, ctx: SMTLIBv2Parser.Var_bindingContext) -> Any: ...
    def visitAttribute(self, ctx: SMTLIBv2Parser.AttributeContext) -> Any: ...
    def visitKeyword(self, ctx: SMTLIBv2Parser.KeywordContext) -> Any: ...
    def visitAttribute_value(self, ctx: SMTLIBv2Parser.Attribute_valueContext) -> Any: ...
    def visitIndex(self, ctx: SMTLIBv2Parser.IndexContext) -> Any: ...
    def visitMatch_case(self, ctx: SMTLIBv2Parser.Match_caseContext) -> Any: ...
    def visitFunction_def(self, ctx: SMTLIBv2Parser.Function_defContext) -> Any: ...
    def visitFunction_dec(self, ctx: SMTLIBv2Parser.Function_decContext) -> Any: ...
    def visitTerminal(self, node: TerminalNode) -> Any: ...

# Error listener
class ErrorListener:
    """ANTLR error listener base class."""
    def syntaxError(
        self,
        recognizer: Any,
        offending_symbol: Any,
        line: int,
        column: int,
        msg: str,
        e: Any,
    ) -> None: ...
